### ISSUE TITLE
Error: Failed to lookup symbol in iOS release (archive) build

### ISSUE THREAD

**Issue by masonhorder** [am15h/tflite_flutter_plugin#88]
Hello,
So when i use my app in debug mode everything works completely fine, no errors and my tflite model runs properly. Then one day I get a support request from a user on the AppStore saying they can't get it to work even though i knew it worked for me. So then I realized it has to do with release mode:

Here is the code that is causing the issue:

Future recognize(List imageList) async {
print("recognize");
debugString += "\nrunning model";
final interpreter = await tfl.Interpreter.fromAsset('v3-model.tflite');
debugString += "\n1";
var input = imageList.reshape([1,224,224,3]);
debugString += "\n2";
List output = List(1*4).reshape([1,4]);
debugString += "\n3";
interpreter.run(input, output);
debugString += "\n4";
_recognition = output;
debugString += "\n5";
interpreter.close();
debugString += "\nmodel done";
// debugString += "Error: $error";

}

Here is the output(release and debug respectively):

Release Mode:

flutter: scan
2021-03-12 10:55:59.159778-0800 Runner[54121:3778134] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, TfLiteModelCreate): symbol not found)
#0 DynamicLibrary.lookup (dart:ffi-patch ffi_dynamic_library_patch.dart:31)
#1 tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart:11)
#2 new Model.fromBuffer (package:tflite_flutter/src/model.dart)
#3 new Interpreter.fromBuffer (package:tflite_flutter/src/interpreter.dart:90)
#4 Interpreter.fromAsset (package:tflite_flutter/src/interpreter.dart:114)

#5 CameraState.recognize (package:filament_left/Screens/camera.dart:125)

#6 CameraState.scanImage (package:filament_left/Screens/camera.dart:111)

2021-03-12 10:55:59.739733-0800 Runner[54121:3778134] flutter: File Uploaded
2021-03-12 10:55:59.743840-0800 Runner[54121:3778214] BackgroundSession <2C5183FE-9D06-46CD-BC99-57D9C1492583> connection to background transfer daemon invalidated

Debug Mode:

flutter: scan
2021-03-12 11:36:48.821404-0800 Runner[54390:3792113] Initialized TensorFlow Lite runtime.
2021-03-12 11:36:49.571281-0800 Runner[54390:3792126] BackgroundSession connection to background transfer daemon invalidated
2021-03-12 11:36:51.313935-0800 Runner[54390:3792113] flutter: postconvert
2021-03-12 11:36:51.314804-0800 Runner[54390:3792113] flutter: coordinate(mainly height) - height than width
2021-03-12 11:36:51.315632-0800 Runner[54390:3792113] flutter: 275.81599473953247
2021-03-12 11:36:51.316580-0800 Runner[54390:3792113] flutter: 490.3395462036133
2021-03-12 11:36:51.316995-0800 Runner[54390:3792113] flutter: coordinate(mainly width) - height than width
2021-03-12 11:36:51.317061-0800 Runner[54390:3792113] flutter: 228.4491491317749
2021-03-12 11:36:51.317102-0800 Runner[54390:3792113] flutter: 406.13182067871094
2021-03-12 11:36:51.317653-0800 Runner[54390:3792113] flutter: coordinate(mainly height) - height than width
2021-03-12 11:36:51.317861-0800 Runner[54390:3792113] flutter: 564.8450231552124
2021-03-12 11:36:51.317916-0800 Runner[54390:3792113] flutter: 1004.1689300537109
2021-03-12 11:36:51.317954-0800 Runner[54390:3792113] flutter: coordinate(mainly width) - height than width
2021-03-12 11:36:51.317989-0800 Runner[54390:3792113] flutter: 514.749641418457
2021-03-12 11:36:51.318323-0800 Runner[54390:3792113] flutter: 915.1104736328125
2021-03-12 11:36:51.318956-0800 Runner[54390:3792113] flutter: 1.76099492754787
2021-03-12 11:36:51.336338-0800 Runner[54390:3792113] flutter: File Uploaded

I believe that the error is coming from this line: Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, TfLiteModelCreate): symbol not found)

Flutter doctor:

[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en)
• Flutter version 2.0.1 at /Users/masonhorder/flutter
• Framework revision c5a4b40 (8 days ago), 2021-03-04 09:47:48 -0800
• Engine revision 40441def69
• Dart version 2.12.0

Thanks so much, Mason

**Comment by am15h** [comment]
The error suggests that `TensorFlowLiteC.framework` is not bundled with the archive build. Did you follow any extra steps that might be required to include a framework in ios archive?

**Comment by masonhorder** [comment]
@am15h I have not done any pre installation or anything like that. I just added the plugin. Nothing is on the documentation for iOS. Thanks, Mason

Here is my podspec.loc:

PODS:
  - camera (0.0.1):
    - Flutter
  - device_info (0.0.1):
    - Flutter
  - Firebase/Analytics (6.33.0):
    - Firebase/Core
  - Firebase/Core (6.33.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.8.3)
  - Firebase/CoreOnly (6.33.0):
    - FirebaseCore (= 6.10.3)
  - Firebase/Storage (6.33.0):
    - Firebase/CoreOnly
    - FirebaseStorage (~> 3.9.0)
  - firebase_analytics (6.3.0):
    - Firebase/Analytics (~> 6.33.0)
    - Firebase/CoreOnly (~> 6.33.0)
    - firebase_core
    - Flutter
  - firebase_core (0.5.3):
    - Firebase/CoreOnly (~> 6.33.0)
    - Flutter
  - firebase_storage (5.2.0):
    - Firebase/CoreOnly (~> 6.33.0)
    - Firebase/Storage (~> 6.33.0)
    - firebase_core
    - Flutter
  - FirebaseAnalytics (6.8.3):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleAppMeasurement (= 6.8.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - FirebaseCore (6.10.3):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebaseStorage (3.9.1):
    - FirebaseCore (~> 6.10)
    - GTMSessionFetcher/Core (~> 1.1)
  - Flutter (1.0.0)
  - FMDB (2.7.5):
    - FMDB/standard (= 2.7.5)
  - FMDB/standard (2.7.5)
  - GoogleAppMeasurement (6.8.3):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - GoogleDataTransport (7.5.1):
    - nanopb (~> 1.30906.0)
  - GoogleUtilities/AppDelegateSwizzler (6.7.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.7.2):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.7.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.7.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.7.2)"
  - GoogleUtilities/Reachability (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.7.2):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.5.0)
  - nanopb (1.30906.0):
    - nanopb/decode (= 1.30906.0)
    - nanopb/encode (= 1.30906.0)
  - nanopb/decode (1.30906.0)
  - nanopb/encode (1.30906.0)
  - path_provider (0.0.1):
    - Flutter
  - PromisesObjC (1.2.12)
  - quick_actions (0.0.1):
    - Flutter
  - sqflite (0.0.2):
    - Flutter
    - FMDB (>= 2.7.5)
  - tflite_flutter (0.1.0):
    - Flutter
  - url_launcher (0.0.1):
    - Flutter

DEPENDENCIES:
  - camera (from `.symlinks/plugins/camera/ios`)
  - device_info (from `.symlinks/plugins/device_info/ios`)
  - Firebase/Analytics
  - firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - firebase_storage (from `.symlinks/plugins/firebase_storage/ios`)
  - Flutter (from `Flutter`)
  - path_provider (from `.symlinks/plugins/path_provider/ios`)
  - quick_actions (from `.symlinks/plugins/quick_actions/ios`)
  - sqflite (from `.symlinks/plugins/sqflite/ios`)
  - tflite_flutter (from `.symlinks/plugins/tflite_flutter/ios`)
  - url_launcher (from `.symlinks/plugins/url_launcher/ios`)

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseInstallations
    - FirebaseStorage
    - FMDB
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - GTMSessionFetcher
    - nanopb
    - PromisesObjC

EXTERNAL SOURCES:
  camera:
    :path: ".symlinks/plugins/camera/ios"
  device_info:
    :path: ".symlinks/plugins/device_info/ios"
  firebase_analytics:
    :path: ".symlinks/plugins/firebase_analytics/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  firebase_storage:
    :path: ".symlinks/plugins/firebase_storage/ios"
  Flutter:
    :path: Flutter
  path_provider:
    :path: ".symlinks/plugins/path_provider/ios"
  quick_actions:
    :path: ".symlinks/plugins/quick_actions/ios"
  sqflite:
    :path: ".symlinks/plugins/sqflite/ios"
  tflite_flutter:
    :path: ".symlinks/plugins/tflite_flutter/ios"
  url_launcher:
    :path: ".symlinks/plugins/url_launcher/ios"

**Comment by masonhorder** [comment]
@am15h Hi, now i am running into this error: ld: library not found for -ltflite_flutter. is this a typo extra l?

**Comment by masonhorder** [comment]
Issue resolved by just recreating the app, just copy over the lib file and pubspec

**Comment by twbabyduck** [comment]
@am15h 
I think I will open this issue again. Somehow it is weird that I cannot manage to use https://pub.dev/packages/tflite and https://pub.dev/packages/tflite_flutter in the same project. I had tried to make it both either static library or dynamic library and it is fine during compile and link stage. However, at the runtime only https://pub.dev/packages/tflite is working but https://pub.dev/packages/tflite_flutter somehow in archive/release mode the error message shows:

Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, TfLiteModelCreate): symbol not found)

Would you mind to comment on this how to fix this issue?

Thanks

**Comment by am15h** [comment]
@twbabyduck Can you please elaborate on what steps have you followed to make them work together in debug mode?

**Comment by twbabyduck** [comment]
**modified tflite.podspec**

```
Pod::Spec.new do |s|
  s.name             = 'tflite'
  s.version          = '1.1.1'
  s.summary          = 'A Flutter plugin for accessing TensorFlow Lite.'
  s.description      = <<-DESC
A Flutter plugin for accessing TensorFlow Lite. Supports both iOS and Android.
                       DESC
  s.homepage         = 'https://github.com/shaqian/flutter_tflite'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Qian Sha' => 'https://github.com/shaqian' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'TensorFlowLiteC'
  s.xcconfig = { 'USER_HEADER_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Private/tflite" "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Flutter" "${PODS_ROOT}/Headers/Public/TensorFlowLite/tensorflow_lite" "${PODS_ROOT}/Headers/Public/tflite" "${PODS_ROOT}/TensorFlowLite/Frameworks/tensorflow_lite.framework/Headers" "${PODS_ROOT}/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/Headers"' }

  s.ios.deployment_target = '13.0'
  s.static_framework = true
end
```

**modified tflite_flutter.podspec** 

```
Pod::Spec.new do |s|
  s.name             = 'tflite_flutter'
  s.version          = '0.1.0'
  s.summary          = 'TensorFlow Lite plugin for Flutter apps.'
  s.description      = <<-DESC
TensorFlow Lite plugin for Flutter apps.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.dependency 'Flutter'
  s.platform = :ios, '8.0'
  
  s.dependency 'TensorFlowLiteC'
  s.ios.deployment_target = '13.0'
  # Flutter.framework does not contain a i386 slice. Only x86_64 simulators are supported.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }
  s.swift_version = '5.0'
  s.library = 'c++'
  # Fail early during build instead of not finding the library during runtime
  s.xcconfig = { 'USER_HEADER_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}/Headers/Public/Flutter"  "${PODS_ROOT}/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/Headers"' }
  s.static_framework = true
end
```

s.dependency will download TensorFlow 2.2.0 under `Pods` folder and tflite seems work fine but tflite_flutter only work in debug mode not release/archive mode. 

The error message is "Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, TfLiteModelCreate): symbol not found)"

**Comment by supratikkoley** [comment]
I am facing the same issue. And I am only using tflite_flutter plugin not tflite. Still facing error.

**Comment by supratikkoley** [comment]
@masonhorder is it solved?
